server:
  port: 8020
  # 应用名称 （nacos会将该名称当做服务名称）
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 47.98.207.91:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public